version: '3'

services:
    mysql:
      build:
        context: ./requirements/mariadb
        args:
          MYSQL_USER: ${MYSQL_USER}
      image: mariadb
      container_name: mariadb
      env_file:
        - .env
      restart: always
