version: '3'

services:
    mariadb:
      build:
        context: ./requirements/mariadb
        args:
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      image: mariadb:rdutenke
      container_name: mariadb
      volumes:
        - mariadb:/var/lib/mysql
      env_file:
        - .env
      restart: always
      networks:
        - rapha-network
    # nginx:
    #   build:
    #     context: ./requirements/nginx
    #   image: nginx:rdutenke
    #   container_name: nginx
    #   restart: always
    #   ports:
    #     - "443:443"
    #   networks:
    #     - rapha-network
    wordpress:
      build:
        context: ./requirements/wordpress
        args:
          WP_DATABASE_NAME: ${WP_DATABASE_NAME}
          WP_DATABASE_USR: ${WP_DATABASE_USR}
          WP_DATABASE_PWD: ${WP_DATABASE_PWD}
          MYSQL_HOST: ${MYSQL_HOST}
          DOMAIN_NAME: ${DOMAIN_NAME}
          WP_TITLE: ${WP_TITLE}
          WP_ADMIN_USR: ${WP_ADMIN_USR}
          WP_ADMIN_PWD: ${WP_ADMIN_PWD}
          WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
          WP_USR: ${WP_USR}
          WP_EMAIL: ${WP_EMAIL}
          WP_PWD: ${WP_PWD}
      image: wordpress:rdutenke
      container_name: wordpress
      volumes:
        - wordpress:/var/www/html
      env_file:
        - .env
      restart: always
      networks:
        - rapha-network
      depends_on:
        - mariadb

volumes:
    wordpress:
        external: true
    mariadb:
        external: true

networks:
    rapha-network:
        driver: bridge